---
substitutions:
    _APP_NAME: testground
    _ENV: test
    
steps:

  # - id: 'sonar_scanner'
  #   name: 'docker.io/sonarsource/sonar-scanner-cli'
  #   args: 
  #   - '-Dproject.settings=sonar.properties'
  
  - id: 'prepare'
    name: 'bash'
    entrypoint: 'cp'
    args: 
    - config/.env.example 
    - config/.env
    
  - id: 'docker_build'
    name: 'gcr.io/cloud-builders/docker'
    args: 
    - build
    - --tag=asia-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/${_APP_NAME}-${_ENV}:${SHORT_SHA}
    - "."
    env: ["PORT=8080"]
    # waitFor:
    #   - "sonar_scanner"
  
  - id: 'docker_push'
    name: 'gcr.io/cloud-builders/docker'
    args:
    - push
    - asia-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/${_APP_NAME}-${_ENV}:${SHORT_SHA}

  # Deploy container image to Cloud Run
  - id: deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
    - run
    - deploy
    - ${_APP_NAME}-${_ENV}
    - --image=asia-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/${_APP_NAME}-${_ENV}:${SHORT_SHA}
    - --vpc-connector=development-vpc-connector
    - --vpc-egress=all
    - --region=asia-southeast2
    - --ingress=all
    - --allow-unauthenticated
    
images: 
- 'asia-docker.pkg.dev/${PROJECT_ID}/${BRANCH_NAME}/${_APP_NAME}-${_ENV}:${SHORT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY
